### ISSUE TITLE
Install Dependencies Issue

### ISSUE THREAD

**Issue by kikegraphics** [dmarx/notebooks#13]
I´m trying to run this notebook but when I run the "install dependencies" cell it shows me this error: 
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.**.
I´m not running locally btw.

any help?. thank you .

**Comment by dmarx** [comment]
this is just pip being noisy, you can ignore that. move on to the next cell as if nothing happened and let me know if you have issues.
